name: "silverbullet"
description: "Silverbullet note taking application"
version: "2.1.9"
slug: "Silverbullet"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/BryanConradHart/homeassistant-addons"
image: "ghcr.io/linuxserver/silverbullet"
startup: services
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Silverbullet web interface"
webui: "http://[HOST]:[PORT:3000]"
options:
  SB_FOLDER: /share/silverbullet/space
  SB_USER: ""
schema:
  SB_FOLDER: str
  SB_USER: "str?"
map:
  - type: share
    read_only: False
environment:
  - SB_FOLDER: "[SB_FOLDER]"
  - SB_USER: "[SB_USER]"